### PR TITLE
Permissions: Make applist searchable

### LINKED ISSUE #146: Search apps in permissions
## Problem

If I have a bunch of apps installed it would be convenient to be able to search for the one I want

## Proposal

a search box inside the first pane that filters the list of apps

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97359812-search-apps-in-permissions?utm_campaign=plugin&utm_content=tracker%2F56794370&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F56794370&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by leolost2605**
- Make the app list searchable
- Also instead of showing a placeholder in the applist it now fills the entire grid

Fixes #146 

Screenshot:
image

### CODE REVIEW

**Review by lenemter — CHANGES_REQUESTED** [review]
Looks like `app_list`  placeholder is missing

`master` (it's broken but it's there)
image

This branch
image

Seems like you wanted to make it look like this, but it's broken for me
image

**Comment by leolost2605** [comment]
Yeah that's definitely not how it should be.
May I ask how you are testing this?

**Comment by lenemter** [comment]
@leolost2605 I just remove the line `app_list.add (app_entry);` (`src/Permissions/PermissionsPlug.vala` line 90) and then it will show placeholder because the `app_list` is empty.

If you're asking about this:


Add `placeholder_stack.set_visible_child (placeholder);` in the end of `construct` block

**Comment by leolost2605** [comment]
> @leolost2605 I just remove the line `app_list.add (app_entry);` (`src/Permissions/PermissionsPlug.vala` line 90) and then it will show placeholder because the `app_list` is empty.

Oh ok that makes sense then. 
Whether the placeholder is shown with this PR is bound to the number of actual applications found by the `AppManager` and not the number of visible children in `app_list`. That's because otherwise it would be shown when searching for an app that isn't installed/not found because of a typo or whatever. 
Currently nothing is shown when this is the case (it's done this way when searching for apps while adding a startup app too so i mimicked this behavior here). Maybe we should still show a placeholder like "No app matching $search_term was found"?

**Comment by lenemter** [comment]
@leolost2605 makes sense, thanks for clarification!

I think such placeholder is a great idea! Please do it :)

**Comment by leolost2605** [comment]
@lenemter done. 
Also when the currently selected row gets hidden it now gets unselected.

**Comment by lenemter** [comment]
What about using a Granite.Widgets.AlertView for the "No Flatpak apps installed" placeholder?

image

**Comment by leolost2605** [comment]
@lenemter done:
Screenshot from 2023-07-06 16 49 00

**Review by lenemter — APPROVED** [review]
Code looks good and works as expected, Great job :tada: I'll ask @danirabbit to review chosen icon of the placeholder and wording.

**Comment by danirabbit** [comment]
Works for me! Nice job :)

**Pull request merged**
