### PR TITLE
Fix install path

### PR DESCRIPTION
**Pull request by peteruithoven**
See:  #13
This uses same path as cmake

### CODE REVIEW

**Comment by peteruithoven** [comment]
This installs the plug inside a folder named `pantheon-applications-plug/`, which might not make sense anymore? I don't think the folder name matters to Switchboard's [PlugsManager](https://github.com/elementary/switchboard/blob/master/lib/PlugsManager.vala), so we could also name it something like `switchboard-plug-applications` (the repo name).

**Comment by danrabbit** [comment]
It looks like the other plugs recently ported to meson aren't installing in individual subfolders anymore. Assigning to @tintou for further clarification

**Comment by tintou** [comment]
Yeah no need to have thousands of subfolders, all plugs should use GResource making the subfolder irrelevant for now, and as you're already installing a plug in the switchboard, there is no reason to keep the -plug in the module name: just some cleanup in the mean time.
Note that the `system`, `hardware`… subfolders are still here to satisfy my OCD :stuck_out_tongue_winking_eye: 
The meson plugs relies on the unreleased version of switchboard, and as we only increase the version number at release time there is currently no way to specify the minimal version number…

**Comment by peteruithoven** [comment]
> Yeah no need to have thousands of subfolders, all plugs should use GResource making the subfolder irrelevant for now, and as you're already installing a plug in the switchboard, there is no reason to keep the -plug in the module name: just some cleanup in the mean time.

I can indeed confirm this, with the latest switchboard it works with and without subfolder. Which makes this PR irrelevant. 

> The meson plugs relies on the unreleased version of switchboard, and as we only increase the version number at release time there is currently no way to specify the minimal version number…

Autch, that's pretty bad that that's not possible, but okay.

**Pull request closed without merging**
